import tkinter as tk 
from tkinter import *
root=Tk()

cuadro = Frame()
cuadro1 = Frame()
cuadro2 = Frame()
cuadro3=Frame()
cuadro4=Frame()
cuadro5=Frame()
cuadro6=Frame()

cuadro.config(width=50,height=50,bg="fuchsia")
cuadro.grid(row=0,column=0)
cuadro1.config(width=50,height=50,bg="fuchsia")
cuadro1.grid(row=0,column=1)
cuadro2.config(width=50,height=50,bg="fuchsia")
cuadro2.grid(row=0,column=2)
cuadro3.config(width=50,height=50,bg="fuchsia")
cuadro3.grid(row=0,column=3)
cuadro4.config(width=50,height=50,bg="fuchsia")
cuadro4.grid(row=0,column=4)
cuadro5.config(width=50,height=50,bg="fuchsia")
cuadro5.grid(row=0,column=5)
cuadro6.config(width=50,height=50,bg="fuchsia")
cuadro6.grid(row=0,column=6)

cuadro7=Frame()
cuadro8=Frame()
cuadro9=Frame()

cuadro7.config(width=50,height=50,bg="fuchsia")
cuadro7.grid(row=1,column=0)
cuadro8.config(width=50,height=50,bg="fuchsia")
cuadro8.grid(row=2,column=0)
cuadro9.config(width=50,height=50,bg="fuchsia")
cuadro9.grid(row=3,column=0)

cuadro10=Frame()
cuadro11=Frame()
cuadro12=Frame()

cuadro10.config(width=50,height=50,bg="fuchsia")
cuadro10.grid(row=3,column=1)
cuadro11.config(width=50,height=50,bg="fuchsia")
cuadro11.grid(row=3,column=2)
cuadro12.config(width=50,height=50,bg="fuchsia")
cuadro12.grid(row=3,column=3)


cuadro13=Frame()
cuadro14=Frame()
cuadro15=Frame()
cuadro16=Frame()

cuadro13.config(width=50,height=50,bg="fuchsia")
cuadro13.grid(row=4,column=0)
cuadro14.config(width=50,height=50,bg="fuchsia")
cuadro14.grid(row=5,column=0)
cuadro15.config(width=50,height=50,bg="fuchsia")
cuadro15.grid(row=6,column=0)
cuadro16.config(width=50,height=50,bg="fuchsia")
cuadro16.grid(row=7,column=0)
root.mainloop()