import tkinter as tk
from tkinter import *

root = Tk()
root.title(" Leoncito")

size = 50 # Tamaño de cada cuadro
#lINEA 0
Cuadro0=Frame()
cuadro1 = Frame()
cuadro2 = Frame()
cuadro3=Frame()
cuadro4=Frame()
cuadro5=Frame()
cuadro6=Frame()
cuadro7=Frame()
cuadro8=Frame()
cuadro9=Frame()
cuadro10=Frame()
cuadro11=Frame()
cuadro12=Frame()
cuadro13=Frame()
cuadro14=Frame()
cuadro15=Frame()
Cuadro0.config(width=size,height=size,bg="white")
Cuadro0.grid(row=0,column=0)
cuadro1.config(width=size,height=size,bg="white")
cuadro1.grid(row=0,column=1)
cuadro2.config(width=size,height=size,bg="white")
cuadro2.grid(row=0,column=2)
cuadro3.config(width=size,height=size,bg="white")
cuadro3.grid(row=0,column=3)
cuadro4.config(width=size,height=size,bg="white")
cuadro4.grid(row=0,column=4)
cuadro5.config(width=size,height=size,bg="white")
cuadro5.grid(row=0,column=5)
cuadro6.config(width=size,height=size,bg="white")
cuadro6.grid(row=0,column=6)
cuadro7.config(width=size,height=size,bg="white")
cuadro7.grid(row=0,column=7)
cuadro8.config(width=size,height=size,bg="white")
cuadro8.grid(row=0,column=8)
cuadro9.config(width=size,height=size,bg="white")
cuadro9.grid(row=0,column=9)
cuadro10.config(width=size,height=size,bg="white")
cuadro10.grid(row=0,column=10)
cuadro11.config(width=size,height=size,bg="white")
cuadro11.grid(row=0,column=11)
cuadro12.config(width=size,height=size,bg="white")
cuadro12.grid(row=0,column=12)
cuadro13.config(width=size,height=size,bg="white")
cuadro13.grid(row=0,column=13)
cuadro14.config(width=size,height=size,bg="white")
cuadro14.grid(row=0,column=14)
cuadro15.config(width=size,height=size,bg="white")
cuadro15.grid(row=0,column=15)
#linea 1 
cuadro16=Frame()
cuadro17=Frame()
cuadro18=Frame()
cuadro19=Frame()
cuadro20=Frame()
cuadro21 =Frame()
cuadro22=Frame()
cuadro23=Frame()
cuadro24=Frame()
cuadro25=Frame()
cuadro26=Frame()
cuadro27=Frame()
cuadro28=Frame()
cuadro29=Frame()
cuadro30=Frame()
cuadro31=Frame()
cuadro16.config(width=size,height=size,bg="white")
cuadro16.grid(row=1,column=0)
cuadro17.config(width=size,height=size,bg="white")
cuadro17.grid(row=1,column=1)
cuadro18.config(width=size,height=size,bg="white")
cuadro18.grid(row=1,column=2)
cuadro19.config(width=size,height=size,bg="white")
cuadro19.grid(row=1,column=3)
cuadro20.config(width=size,height=size,bg="white")
cuadro20.grid(row=1,column=4)
cuadro21.config(width=size,height=size,bg="orange")
cuadro21.grid(row=1,column=5)
cuadro22.config(width=size,height=size,bg="orange")
cuadro22.grid(row=1,column=6)
cuadro23.config(width=size,height=size,bg="white")
cuadro23.grid(row=1,column=7)
cuadro24.config(width=size,height=size,bg="orange")
cuadro24.grid(row=1,column=8)
cuadro25.config(width=size,heigh=size,bg="orange")
cuadro25.grid(row=1,column=9)
cuadro26.config(width=size,height=size,bg="white")
cuadro26.grid(row=1,column=10)
cuadro27.config(width=size,height=size,bg="white")
cuadro27.grid(row=1,column=11)
cuadro28.config(width=size,height=size,bg="white")
cuadro28.grid(row=1,column=12)
cuadro29.config(width=size,height=size,bg="white")
cuadro29.grid(row=1,column=13)
cuadro30.config(width=size,height=size,bg="white")
cuadro30.grid(row=1,column=14)
cuadro31.config(width=size,height=size,bg="white")
cuadro31.grid(row=1,column=15)
#linea 2
cuadro32=Frame()
cuadro33=Frame()
cuadro34=Frame()
cuadro35=Frame()
cuadro36=Frame()
cuadro37=Frame()
cuadro38=Frame()
cuadro39=Frame()
cuadro40=Frame()
cuadro41=Frame()
cuadro42=Frame()
cuadro43=Frame()
cuadro44=Frame()
cuadro45=Frame()
cuadro46=Frame()
cuadro47=Frame()

cuadro32.config(width=size,height=size,bg="white")
cuadro32.grid(row=2,column=0)
cuadro33.config(width=size,height=size,bg="white")
cuadro33.grid(row=2,column=1)
cuadro34.config(width=size,height=size,bg="peach puff")
cuadro34.grid(row=2,column=2)
cuadro35.config(width=size,height=size,bg="peach puff")
cuadro35.grid(row=2,column=3)
cuadro36.config(width=size,height=size,bg="orange")
cuadro36.grid(row=2,column=4)
cuadro37.config(width=size,height=size,bg="orange")
cuadro37.grid(row=2,column=5)
cuadro38.config(width=size,height=size,bg="orange")
cuadro38.grid(row=2,column=6)
cuadro39.config(width=size,height=size,bg="orange")
cuadro39.grid(row=2,column=7)
cuadro40.config(width=size,height=size,bg="orange")
cuadro40.grid(row=2,column=8)
cuadro41.config(width=size,height=size,bg="orange")
cuadro41.grid(row=2,column=9)
cuadro42.config(width=size,height=size,bg="orange")
cuadro42.grid(row=2,column=10)
cuadro43.config(width=size,height=size,bg="orange")
cuadro43.grid(row=2,column=11)
cuadro44.config(width=size,height=size,bg="peach puff")
cuadro44.grid(row=2,column=12)
cuadro45.config(width=size,height=size,bg="peach puff")
cuadro45.grid(row=2,column=13)
cuadro46.config(width=size,height=size,bg="white")
cuadro46.grid(row=2,column=14)
cuadro47.config(width=size,height=size,bg="white")
cuadro47.grid(row=2,column=15)

#linea 3 
cuadro48=Frame()
cuadro49=Frame()
cuadro50=Frame()
cuadro51=Frame()
cuadro52=Frame()
cuadro53=Frame()
cuadro54=Frame()
cuadro55=Frame()
cuadro56=Frame()
cuadro56=Frame()
cuadro57=Frame()
cuadro58=Frame()
cuadro59=Frame()
cuadro60=Frame()
cuadro61=Frame()
cuadro62=Frame()
cuadro63=Frame()
cuadro64=Frame()

cuadro48.config(width=size,height=size,bg="white")
cuadro48.grid(row=3,column=0)
cuadro49.config(width=size,height=size,bg="orange")
cuadro49.grid(row=3,column=1)
cuadro50.config(width=size,height=size,bg="peach puff")
cuadro50.grid(row=3,column=2)
cuadro51.config(width=size,height=size,bg="white")
cuadro51.grid(row=3,column=3)
cuadro52.config(width=size,height=size,bg="orange")
cuadro52.grid(row=3,column=4)
cuadro53.config(width=size,height=size,bg="peach puff")
cuadro53.grid(row=3,column=5)
cuadro54.config(width=size,height=size,bg="peach puff")
cuadro54.grid(row=3,column=6)
cuadro55.config(width=size,height=size,bg="peach puff")
cuadro55.grid(row=3,column=7)
cuadro56.config(width=size,height=size,bg="peach puff")
cuadro56.grid(row=3,column=8)
cuadro57.config(width=size,height=size,bg="peach puff")
cuadro57.grid(row=3,column=9)
cuadro58.config(width=size,height=size,bg="peach puff")
cuadro58.grid(row=3,column=10)
cuadro59.config(width=size,height=size,bg="orange")
cuadro59.grid(row=3,column=11)
cuadro60.config(width=size,height=size,bg="white")
cuadro60.grid(row=3,column=12)
cuadro61.config(width=size,height=size,bg="peach puff")
cuadro61.grid(row=3,column=13)
cuadro62.config(width=size,height=size,bg="orange")
cuadro62.grid(row=3,column=14)
cuadro63.config(width=size,height=size,bg="white")
cuadro63.grid(row=3,column=15)

#linea4
cuadro64=Frame()
cuadro65=Frame()
cuadro66=Frame()
cuadro67=Frame()
cuadro68=Frame()
cuadro69=Frame()
cuadro70=Frame()
cuadro71=Frame()
cuadro72=Frame()
cuadro73=Frame()
cuadro74=Frame()
cuadro75=Frame()
cuadro76=Frame()
cuadro77=Frame()
cuadro78=Frame()
cuadro79=Frame()


cuadro64.config(width=size,height=size,bg="white")
cuadro64.grid(row=4,column=0)
cuadro65.config(width=size,height=size,bg="orange")
cuadro65.grid(row=4,column=1)
cuadro66.config(width=size,height=size,bg="orange")
cuadro66.grid(row=4,column=2)
cuadro67.config(width=size,height=size,bg="orange")
cuadro67.grid(row=4,column=3)
cuadro68.config(width=size,height=size,bg="peach puff")
cuadro68.grid(row=4,column=4)
cuadro69.config(width=size,height=size,bg="peach puff")
cuadro69.grid(row=4,column=5)
cuadro70.config(width=size,height=size,bg="peach puff")
cuadro70.grid(row=4,column=6)
cuadro71.config(width=size,height=size,bg="peach puff")
cuadro71.grid(row=4,column=7)
cuadro72.config(width=size,height=size,bg="peach puff")
cuadro72.grid(row=4,column=8)
cuadro73.config(width=size,height=size,bg="peach puff")
cuadro73.grid(row=4,column=9)
cuadro74.config(width=size,height=size,bg="peach puff")
cuadro74.grid(row=4,column=10)
cuadro75.config(width=size,height=size,bg="peach puff")
cuadro75.grid(row=4,column=11)
cuadro76.config(width=size,height=size,bg="orange")                                                                                                                                                                                                                                                                                                                                   
cuadro76.grid(row=4,column=12)
cuadro77.config(width=size,height=size,bg="orange")   
cuadro77.grid(row=4,column=13)
cuadro78.config(width=size,height=size,bg="orange")   
cuadro78.grid(row=4,column=14)
cuadro79.config(width=size,height=size,bg="white")   
cuadro79.grid(row=4,column=15)

#linea#5
cuadro80=Frame()
cuadro81=Frame()
cuadro82=Frame()
cuadro83=Frame()
cuadro84=Frame()
cuadro85=Frame()
cuadro86=Frame()
cuadro87=Frame()
cuadro88=Frame()
cuadro89=Frame()
cuadro90=Frame()
cuadro91=Frame()
cuadro92=Frame()
cuadro93=Frame()
cuadro94=Frame()
cuadro95=Frame()

cuadro80.config(width=size,height=size,bg="white")
cuadro80.grid(row=5,column=0)
cuadro81.config(width=size,height=size,bg="white")
cuadro81.grid(row=5,column=1)
cuadro82.config(width=size,height=size,bg="orange")
cuadro82.grid(row=5,column=2)
cuadro83.config(width=size,height=size,bg="peach puff")
cuadro83.grid(row=5,column=3)
cuadro84.config(width=size,height=size,bg="peach puff")
cuadro84.grid(row=5,column=4)
cuadro85.config(width=size,height=size,bg="peach puff")
cuadro85.grid(row=5,column=5)
cuadro86.config(width=size,height=size,bg="peach puff")
cuadro86.grid(row=5,column=6)
cuadro87.config(width=size,height=size,bg="peach puff")
cuadro87.grid(row=5,column=7)
cuadro88.config(width=size,height=size,bg="peach puff")
cuadro88.grid(row=5,column=8)
cuadro89.config(width=size,height=size,bg="peach puff")
cuadro89.grid(row=5,column=9)
cuadro90.config(width=size,height=size,bg="peach puff")
cuadro90.grid(row=5,column=10)
cuadro91.config(width=size,height=size,bg="peach puff")
cuadro91.grid(row=5,column=11)
cuadro92.config(width=size,height=size,bg="peach puff")
cuadro92.grid(row=5,column=12)
cuadro93.config(width=size,height=size,bg="orange")
cuadro93.grid(row=5,column=13)
cuadro94.config(width=size,height=size,bg="white")
cuadro94.grid(row=5,column=14)
cuadro95.config(width=size,height=size,bg="white")
cuadro95.grid(row=5,column=15)

#linea6
cuadro96=Frame()
cuadro97=Frame()
cuadro98=Frame()
cuadro99=Frame()
cuadro100=Frame()
cuadro101=Frame()
cuadro102=Frame()
cuadro103=Frame()
cuadro104=Frame()
cuadro105=Frame()
cuadro106=Frame()
cuadro105=Frame()
cuadro106=Frame()
cuadro107=Frame()
cuadro108=Frame()
cuadro109=Frame()
cuadro110=Frame()
cuadro111=Frame()

cuadro96.config(width=size,height=size,bg="white")
cuadro96.grid(row=6,column=0)
cuadro97.config(width=size,height=size,bg="orange")
cuadro97.grid(row=6,column=1)
cuadro98.config(width=size,height=size,bg="orange")
cuadro98.grid(row=6,column=2)
cuadro99.config(width=size,height=size,bg="peach puff")
cuadro99.grid(row=6,column=3)
cuadro100.config(width=size,height=size,bg="peach puff")
cuadro100.grid(row=6,column=4)
cuadro101.config(width=size,height=size,bg="black")
cuadro101.grid(row=6,column=5)
cuadro102.config(width=size,height=size,bg="peach puff")
cuadro102.grid(row=6,column=6)
cuadro103.config(width=size,height=size,bg="peach puff")
cuadro103.grid(row=6,column=7)
cuadro104.config(width=size,height=size,bg="peach puff")
cuadro104.grid(row=6,column=8)
cuadro105.config(width=size,height=size,bg="black")
cuadro105.grid(row=6,column=9)
cuadro106.config(width=size,height=size,bg="peach puff")
cuadro106.grid(row=6,column=10)
cuadro107.config(width=size,height=size,bg="peach puff")
cuadro107.grid(row=6,column=11)
cuadro108.config(width=size,height=size,bg="peach puff")
cuadro108.grid(row=6,column=12)
cuadro109.config(width=size,height=size,bg="orange")
cuadro109.grid(row=6,column=13)
cuadro110.config(width=size,height=size,bg="orange")
cuadro110.grid(row=6,column=14)
cuadro111.config(width=size,height=size,bg="white")
cuadro111.grid(row=6,column=15)

#lista 7
cuadro112=Frame()
cuadro113=Frame()
cuadro114=Frame()
cuadro115=Frame()
cuadro116=Frame()
cuadro117=Frame()
cuadro118=Frame()
cuadro119=Frame()
cuadro120=Frame()
cuadro121=Frame()
cuadro122=Frame()
cuadro123=Frame()
cuadro124=Frame()
cuadro125=Frame()
cuadro126=Frame()
cuadro127=Frame()

cuadro112.config(width=size,height=size,bg="white")
cuadro112.grid(row=7,column=0)
cuadro113.config(width=size,height=size,bg="orange")
cuadro113.grid(row=7,column=1)
cuadro114.config(width=size,height=size,bg="orange")
cuadro114.grid(row=7,column=2)
cuadro115.config(width=size,height=size,bg="peach puff")
cuadro115.grid(row=7,column=3)
cuadro116.config(width=size,height=size,bg="pink")
cuadro116.grid(row=7,column=4)
cuadro117.config(width=size,height=size,bg="peach puff")
cuadro117.grid(row=7,column=5)
cuadro118.config(width=size,height=size,bg="white")
cuadro118.grid(row=7,column=6)
cuadro119.config(width=size,height=size,bg="black")
cuadro119.grid(row=7,column=7)
cuadro120.config(width=size,height=size,bg="white")
cuadro120.grid(row=7,column=8)
cuadro121.config(width=size,height=size,bg="peach puff")
cuadro121.grid(row=7,column=9)
cuadro122.config(width=size,height=size,bg="pink")
cuadro122.grid(row=7,column=10)
cuadro123.config(width=size,height=size,bg="peach puff")
cuadro123.grid(row=7,column=11)
cuadro124.config(width=size,height=size,bg="peach puff")
cuadro124.grid(row=7,column=12)
cuadro125.config(width=size,height=size,bg="orange")
cuadro125.grid(row=7,column=13)
cuadro126.config(width=size,height=size,bg="orange")
cuadro126.grid(row=7,column=14)
cuadro127.config(width=size,height=size,bg="white")
cuadro127.grid(row=7,column=15)

#linea 8
cuadro128=Frame()
cuadro129=Frame()
cuadro130=Frame()
cuadro131=Frame()
cuadro132=Frame()
cuadro133=Frame()
cuadro134=Frame()
cuadro135=Frame()
cuadro136=Frame()
cuadro137=Frame()
cuadro138=Frame()
cuadro139=Frame()
cuadro140=Frame()
cuadro141=Frame()
cuadro142=Frame()
cuadro145=Frame()

cuadro128.config(width=size,height=size,bg="white")
cuadro128.grid(row=8,column=0)
cuadro129.config(width=size,height=size,bg="white")
cuadro129.grid(row=8,column=1)
cuadro130.config(width=size,height=size,bg="orange")
cuadro130.grid(row=8,column=2)
cuadro131.config(width=size,height=size,bg="orange")
cuadro131.grid(row=8,column=3)
cuadro132.config(width=size,height=size,bg="peach puff")
cuadro132.grid(row=8,column=4)
cuadro133.config(width=size,height=size,bg="peach puff")
cuadro133.grid(row=8,column=5)
cuadro134.config(width=size,height=size,bg="white")
cuadro134.grid(row=8,column=6)
cuadro135.config(width=size,height=size,bg="white")
cuadro135.grid(row=8,column=7)
cuadro136.config(width=size,height=size,bg="white")
cuadro136.grid(row=8,column=8)
cuadro137.config(width=size,height=size,bg="peach puff")
cuadro137.grid(row=8,column=9)
cuadro138.config(width=size,height=size,bg="peach puff")
cuadro138.grid(row=8,column=10)
cuadro139.config(width=size,height=size,bg="peach puff")
cuadro139.grid(row=8,column=11)
cuadro140.config(width=size,height=size,bg="orange")
cuadro140.grid(row=8,column=12)
cuadro141.config(width=size,height=size,bg="orange")
cuadro141.grid(row=8,column=13)
cuadro142.config(width=size,height=size,bg="white")
cuadro142.grid(row=8,column=14)
cuadro145.config(width=size,height=size,bg="white")
cuadro145.grid(row=8,column=15)

#linea 9 
cuadro146=Frame()
cuadro147=Frame()
cuadro148=Frame()
cuadro149=Frame()
cuadro150=Frame()
cuadro151=Frame()
cuadro152=Frame()
cuadro153=Frame()
cuadro154=Frame()
cuadro155=Frame()
cuadro156=Frame()
cuadro157=Frame()
cuadro158=Frame()
cuadro159=Frame()
cuadro160=Frame()
cuadro161=Frame()

cuadro146.config(width=size,height=size,bg="white")
cuadro146.grid(row=9,column=0)
cuadro147.config(width=size,height=size,bg="white")
cuadro147.grid(row=9,column=1)
cuadro148.config(width=size,height=size,bg="white")
cuadro148.grid(row=9,column=2)
cuadro149.config(width=size,height=size,bg="orange")
cuadro149.grid(row=9,column=3)
cuadro150.config(width=size,height=size,bg="orange")
cuadro150.grid(row=9,column=4)
cuadro151.config(width=size,height=size,bg="orange")
cuadro151.grid(row=9,column=5)
cuadro152.config(width=size,height=size,bg="orange")
cuadro152.grid(row=9,column=6)
cuadro153.config(width=size,height=size,bg="orange")
cuadro153.grid(row=9,column=7)
cuadro154.config(width=size,height=size,bg="orange")
cuadro154.grid(row=9,column=8)
cuadro155.config(width=size,height=size,bg="orange")
cuadro155.grid(row=9,column=9)
cuadro156.config(width=size,height=size,bg="orange")
cuadro156.grid(row=9,column=10)
cuadro157.config(width=size,height=size,bg="orange")
cuadro157.grid(row=9,column=11)
cuadro158.config(width=size,height=size,bg="orange")
cuadro158.grid(row=9,column=12)
cuadro159.config(width=size,height=size,bg="white")
cuadro159.grid(row=9,column=13)
cuadro160.config(width=size,height=size,bg="white")
cuadro160.grid(row=9,column=14)
cuadro161.config(width=size,height=size,bg="white")
cuadro161.grid(row=9,column=15)

#linea10
cuadro162=Frame()
cuador163=Frame()
cuadro164=Frame()
cuadro165=Frame()
cuadro166=Frame()
cuadro167=Frame()
cuadro168=Frame()
cuadro169=Frame()
cuadro170=Frame()
cuadro171=Frame()
cuadro172=Frame()
cuadro173=Frame()
cuadro174=Frame()
cuadro175=Frame()
cuadro176=Frame()
cuadro177=Frame()

cuadro162.config(width=size,height=size,bg="white")
cuadro162.grid(row=10,column=0)
cuador163.config(width=size,height=size,bg="white")
cuador163.grid(row=10,column=1)
cuadro164.config(width=size,height=size,bg="white")
cuadro164.grid(row=10,column=2)
cuadro165.config(width=size,height=size,bg="white")
cuadro165.grid(row=10,column=3)
cuadro166.config(width=size,height=size,bg="orange")
cuadro166.grid(row=10,column=4)
cuadro167.config(width=size,height=size,bg="orange")
cuadro167.grid(row=10,column=5)
cuadro168.config(width=size,height=size,bg="white")
cuadro168.grid(row=10,column=6)
cuadro169.config(width=size,height=size,bg="orange")
cuadro169.grid(row=10,column=7)
cuadro170.config(width=size,height=size,bg="white")
cuadro170.grid(row=10,column=8)
cuadro171.config(width=size,height=size,bg="orange")
cuadro171.grid(row=10,column=9)
cuadro172.config(width=size,height=size,bg="orange")
cuadro172.grid(row=10,column=10)
cuadro173.config(width=size,height=size,bg="white")
cuadro173.grid(row=10,column=11)
cuadro174.config(width=size,height=size,bg="white")
cuadro174.grid(row=10,column=12)
cuadro175.config(width=size,height=size,bg="white")
cuadro175.grid(row=10,column=13)
cuadro176.config(width=size,height=size,bg="white")
cuadro176.grid(row=10,column=14)
cuadro177.config(width=size,height=size,bg="white")
cuadro177.grid(row=10,column=15)

root.mainloop()
